// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgvgkucrmtugckcefryn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNndmdrdWNybXR1Z2NrY2VmcnluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTc1NzIsImV4cCI6MjA2NDA3MzU3Mn0.-MiSRTJCrLjDpUCHyZH2HRZ7Q2qswi1lFeR3MTi8kzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);